### ISSUE TITLE
🔨 [Refactor] Base URL env 파일로 작성

### ISSUE THREAD

**Issue by eugene028** [prgrms-fe-devcourse/FEDC4_PETTALK_Yrnana#4]
## 🔨 리팩토링이 필요한 부분
현재 프로그래머스 Base URL이 커밋기록에 올라와있는 상황이라 이를 .env파일로 따로 빼 놓을 예정입니다!
## 리팩토링 작업 브랜치
- dev
## ☑ Refactoring TODO
- [x] base URL 제거 및 env 파일로 분리
- [x] .env 파일 팀원들에게 전달

**Comment by JeongWuk** [comment]
👍👍👍
